### ISSUE TITLE
CLA Assistant not showing as signed in PR

### ISSUE THREAD

**Issue by debragail** [aragon/aragon-monthly#132] opened 2018-05-27 06:08 UTC
When trying to a new PR CLA assistant is signed but shows as unsigned. Created new PR to exemplify issue:

https://github.com/aragon/aragon-monthly/pull/131
<img width="1680" alt="screen shot 2018-05-26 at 23 04 27" src="https://user-images.githubusercontent.com/552529/40582989-96479ad0-6139-11e8-9053-d413fe552e30.png">
<img width="791" alt="screen shot 2018-05-26 at 23 08 07" src="https://user-images.githubusercontent.com/552529/40582993-b4aabaf2-6139-11e8-9778-6ffd56c31c23.png">

**Comment by debragail** [comment] 2018-05-27 06:10
there is an email address already associated:
<img width="778" alt="screen shot 2018-05-26 at 23 09 31" src="https://user-images.githubusercontent.com/552529/40583007-ef215448-6139-11e8-895a-a15dfa32fcab.png">

**Comment by debragail** [comment] 2018-05-27 06:13
![Uploading Screen Shot 2018-05-26 at 23.11.23.png…]()

**Comment by debragail** [comment] 2018-05-27 06:14
<img width="1222" alt="screen shot 2018-05-26 at 20 44 25" src="https://user-images.githubusercontent.com/552529/40583032-842493e8-613a-11e8-9328-431714dc8d12.png">

**Comment by debragail** [comment] 2018-05-27 06:15
<img width="1242" alt="screen shot 2018-05-26 at 23 11 23" src="https://user-images.githubusercontent.com/552529/40583039-a23c7bfc-613a-11e8-8eb6-6b2ff43c5225.png">

**Comment by debragail** [comment] 2018-05-27 13:03
I just created a new account and made a test pull request and it cleared and showed i signed the CLA even tho I never did and it was the first action I did with the new account.
<img width="1154" alt="screen shot 2018-05-27 at 06 00 37" src="https://user-images.githubusercontent.com/552529/40586190-ad7ab70c-6173-11e8-9e39-1eb2dbf4abe6.png">

new user: @ophe1ia

https://github.com/aragon/aragon-monthly/pull/133

**Comment by Smokyish** [comment] 2018-05-27 16:49
@debragail Looking through these trying to get to the bottom of this to solve the issue.

One weird thing i'm noticing is that the commit in #131 shows that the commit was made by "O" 20 days ago, where i would think it should show your account and pic.

Also, looking at your fork of the repo, it shows `This branch is 122 commits ahead, 124 commits behind aragon:master.`, could you try syncing the fork with `master` to see if that helps?
```
git fetch upstream
git checkout master
git merge upstream/master
```
in the fork dir should do the trick.

And then try creating a new Pull Request with a new commit that originates from your account and email, hopefully that might help.

**Comment by Smokyish** [comment] 2018-05-27 17:01
A recap of what seems to be the issue:

From #133 we can see that the CLA appears to only want CLA signatures from the people who have made commits, not the person creating the PR.

In #131 we can see that the only commit was added by "O", who doesn't seem to be a registered account (according to the CLA Assistant), and there is the discrepancy between the username that created the PR and who created the commit (https://github.com/aragon/aragon-monthly/pull/131/commits/a21673d5a1797b29fb9c8e59c541b4b02ff09065).

And with that, the fix for getting the CLA properly signed, the CLA should be signed by the person/account that creates the commit(s) that introduce changes and make up the Pull Request and the account creating the PR is basically ignored since it could be anyone, but the PR itself doesn't introduce changes where as the commits do.

**Comment by ophe1ia** [comment] 2018-05-27 17:04
I made the commit from the same account but it is showing as O.  I
troubleshot this with github and I’m unsure why this is only happening on
Aragon as I’m a contributor on Status and haven’t seen this behavior.

I’ll submit a new PR and see if it’s persists.

**Comment by Smokyish** [comment] 2018-05-27 17:33
@debragail @ophe1ia 
> Aragon as I’m a contributor on Status and haven’t seen this behavior.

Status doesn't seem to have a CLA check in place, so that's why there wouldn't be a similar issue on their repos.

**Comment by debragail** [comment] 2018-05-27 20:53
@Smokyish I'm aware that Status doesnt have the CLA you have, however I was pointing out I never submitted a PR as O until I tried to use the CLA Assistant on your repo.  I previously had a private email address and had to make it public.  Perhaps you should try to recreate that use case.

**Comment by ophe1ia** [comment] 2018-05-27 21:18
It’s really kinda a mess, I apologize but it’s worth figuring out.  I’m now commiting as debragail which is good but now I can’t figure out why all those commits are occurring on each PR.  See my comment on my latest pull request to fix a strange git fragment that made its way into an .md somehow.  I’d imagine CLA is buggy and I’d remove it for the time being to see if we have the same problems.  Again I’d try to recreate these issues and troubleshoot CLA.  I also mention I’ve had no problem with contributing to Status to highlight the issues that might surround CLAs access to the git API.

**Comment by Smokyish** [comment] 2018-05-28 07:40
@debragail @ophe1ia Let's continue investigating, but the CLA doesn't really have anything to do with this, it doesn't make any changes to any files or commits, it's merely a outside check that the contributor has signed the Contributor License Agreement, it's working as it should actually, it checks to see if the person who has commits has signed the CLA or not.

I can try to do a fresh fork of the repo as well, but as i commented in #137, it looks like that the issue currently is in your commit history for some reason.

I reset the repo along with daos.md 3 days ago, so the fragments you mention could be caused by that if you haven't synced all your content locally and remotely. As long as your local and remote master is in par with https://github.com/aragon/aragon-monthly/commit/38ed351f5629add0f525e688765a5d39d54e4e00 all new commits/branches created after that should be fine moving forward.

**Comment by ophe1ia** [comment] 2018-05-28 22:01
Well that change to #94 is the original commit I did so I think we can close that bounty.  As far as the 126 commits, maybe that is being fetched from upstream?  I’d still like to to be able to work on compiling issue 04.  Im going to do another new clone and work from there in my local repo.  I’m not sure how the O commit happened but it seems to be fixed now that I have a public email address.  Again, I’d be curious if people with private email addresses would have a similar bug.  So now that the CLA is fixed nothing is barring me from the other bugs, aside from mangled PRs which i’ll be careful to track and continue to try to understand.

Deb

**Comment by Smokyish** [comment] 2018-05-29 10:51
@debragail @ophe1ia In your local version that you have cloned, you could use `git config user.email` to see which email is set for that specific directory/repo, and you can set it to something else with `git config user.email "email@host.com"` in case you have a need for that.

**Comment by Smokyish** [comment] 2018-06-07 13:16
Hi @debragail @ophe1ia Have you been able to resolve this issue?

**Comment by ophe1ia** [comment] 2018-06-17 04:37
Still haven’t been able to resolve the issue.  Was curious if I could be paid for the article I uploaded since it was merged in even though my PR was closed.

Deb

**Comment by krrisis** [comment] 2018-10-22 12:24
hey @debragail sorry for the late reply! The PR/issue in question apparently did not have a bounty associated, and there was no successful PR we think for a bounty? We can however reward you in some way for helping out if you can send us an address!

**Comment by ophe1ia** [comment] 2018-10-22 17:03
Thanks so much!  Would love to contribute more now that everything has moved to Gitcoin.

Here is my ethereum/erc20 compatible wallet:

0x96Cc574509e79658aD36D9ca90CfBb60960EfDF2

**Comment by ophe1ia** [comment] 2018-11-01 20:09
Just following up on this.  Would like to work on this more once I see payment.

Deb

**Comment by ophe1ia** [comment] 2018-11-07 00:03
Hi following up on this.

**Comment by krrisis** [comment] 2018-11-13 21:35
hey @ophe1ia - I checked with Tatu and just sent you 30 ANT for this, tx [here](https://etherscan.io/tx/0xc5c5d598da0fd3d6a3ae19e0d0a85f04a03b5b2b40eb90da98eb2c27eb54ffa4) - thx again!

**Comment by ophe1ia** [comment] 2018-11-13 22:09
Thank you!

**Closed** 2018-11-27 01:31 UTC
