### ISSUE TITLE
Issue 12 - add Resources for decentralized organizing to News

### ISSUE THREAD

**Issue by krrisis** [aragon/aragon-monthly#306] opened 2018-12-31 10:38 UTC
### Request type:
 _News_

### Description of the requested content

https://hackmd.io/s/Skh_dXNbE

**Comment by john-light** [comment] 2018-12-31 23:51
Duplicate of https://github.com/aragon/aragon-monthly/issues/301

**Closed by john-light** 2018-12-31 23:51 UTC
Labels: duplicate

**Comment by krrisis** [comment] 2019-01-02 17:43
haha, so strange! I really looked for this and when typing it, it didn't show up 🙈 If we continue with the monthly we'll need to implement that bot one day :)
